"""
Director Models
===============
Immutable data transfer objects for communication within the director package.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field


def _new_session_id() -> str:
    """Generate a new unique session identifier."""
    return str(uuid.uuid4())


@dataclass(frozen=True)
class DirectorRequest:
    """
    An immutable request sent to the Director.

    Attributes:
        query:      The text input/instruction from the user.
        session_id: Session identifier to group conversation history context.
        metadata:   Optional tracing or context data.
    """

    query: str
    session_id: str = field(default_factory=_new_session_id)
    metadata: dict[str, object] = field(default_factory=dict)


@dataclass(frozen=True)
class DirectorResponse:
    """
    An immutable response returned by the Director.

    Attributes:
        success:     True if the request was completed without error.
        result:      The output generated by the specialist worker (None on failure).
        error:       Human-readable error description (None on success).
        duration_ms: Total execution time in milliseconds.
        plan:        The ExecutionPlan that was constructed and run.
    """

    success: bool
    result: object = None
    error: str | None = None
    duration_ms: float = 0.0
    plan: ExecutionPlan | None = None


@dataclass(frozen=True)
class DirectorDecision:
    """
    An immutable routing decision made by the Router.

    Attributes:
        worker_id: The ID of the worker selected to handle the request.
        reason:    The explanation or rule match for selecting this worker.
    """

    worker_id: str
    reason: str


@dataclass(frozen=True)
class ExecutionStep:
    """
    An immutable step within an execution plan.
    """
    id: str
    worker_id: str
    input_data: object
    description: str = ""
    timeout_seconds: float = 30.0
    retry_count: int = 0


@dataclass
class ExecutionPlan:
    """
    A plan containing steps to execute.
    """
    intent: str
    task_classification: str
    steps: list[ExecutionStep] = field(default_factory=list)
    context_block: str = ""

